# Generated by Django 3.2.3 on 2021-05-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210516_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(default='https://image.freepik.com/free-vector/content-author-writer-job-concept_74855-7064.jpg', max_length=2083),
        ),
    ]
