# Generated by Django 3.2.3 on 2021-05-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png', max_length=2083),
        ),
    ]
