# Generated by Django 3.2.3 on 2021-05-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='local',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='private',
            old_name='private',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='unread',
            old_name='unread',
            new_name='status',
        ),
    ]
